name: Build and Push Docker image

on:

 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker HUB
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: anilty/nodejs-app

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          file: app/Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  update-manifest:
    name: Update Kubernetes Manifests
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Deployment YAML
        run: |
          sed -i 's|image: anilty/nodejs-app:.*|image: anilty/nodejs-app:${{ github.run_number }}|' k8s/deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image to anilty/nodejs-app:${{ github.run_number }}"
          git push

  sync-argocd:
    name: Sync ArgoCD
    runs-on: ubuntu-latest
    needs: update-manifest

    steps:
      - name: Sync ArgoCD App
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
          "https://dlytica-devops-aniltyata.eastus.cloudapp.azure.com:30616/api/v1/applications/nodejs-app/sync"

